model:
  name: mlp_ma # fpn_inception
  network_architecture:
    en_embed_dims: [3,32,64,128,256]
    grid_size: [8,8]
    block_size: [8,8]
    grid_gmlp_factor: 2
    block_gmlp_factor: 2
    input_proj_factor: 2
    channels_reduction: 4
    out_channels: 65
    cell_size: 8
    
resize_image: [240,320]