data:
  synth_dir: data/synth/
  dataset_names: [COCO]
  COCO:
    images_path: data/COCO
    labels_path: data/COCO_raw_ground_truth
    valid_val_split_file: datasets/coco_valid_val_image_names.txt
    valid_train_split_file: datasets/coco_valid_train_image_names.txt
    patch_size: 192

  GOPRO:
    images_path: data/GOPRO_Large/train/
    sequences_split_path: datasets/GOPRO_sequences_split
    labels_path: data/GOPRO_raw_ground_truth/train
    patch_size: 256

  homographic:
    perspective: 0.2
    rotation: 25
    scale: 0.2
    
  train_batch_size: 4
  val_batch_size: 1

  train_num_workers: 12
  val_num_workers: 12


model:
  name: mlp_ma_pos
  network_architecture:
    en_embed_dims: [3,32,64,128,256]
    grid_size: [8,8]
    block_size: [8,8]
    grid_gmlp_factor: 2
    block_gmlp_factor: 2
    input_proj_factor: 2
    channels_reduction: 4
    out_channels: 65
  optimizer:
    name: adam
    lr: 0.0001
    weight_decay: 0.0005
    total_epochs: 100
    decay_step_list: [0.6, 0.8]
    warmup_epoch: 4
    lr_decay: 0.1
    lr_clip: 0.0000001
  scheduler:
    name: linear
    start_epoch: 60 # 50
    min_lr: 0.0000001
    decay_rate: 0.5
  anchor_loss: softmax
  unsuper_loss:
    downsample: 8
    image_shape: [192,192]
    correspond: 8
    usp_weight: 2.0
    position_weight: 1.0
    score_weight: 2.0
    rep_weight: 2.0
    uni_weight: 0.25
  cell_size: 8
  nms_size: 15
  
ckpt_save_interval: 10
max_ckpt_save_num: 30